### PR TITLE
feature: add diagram of vcl-range_proof

### PR DESCRIPTION
**Pull request by leeduckgo**
增加流程图，便于理解。

### CODE REVIEW

**Review by HaoXuan40404 — APPROVED** [review]
LGTM 👍

**Comment by leeduckgo** [comment]
updated

**Comment by leeduckgo** [comment]
> Could please rename "range_prove" to "range_proof" in the image for the variable returned by prove_range(value_secret)?

updated

**Review by HaoXuan40404 — CHANGES_REQUESTED** [review]
parameter name should be uniform, e.g. credit_value, value_credit, range_proof, range_prove

**Comment by leeduckgo** [comment]
> parameter name should be uniform, e.g. credit_value, value_credit, range_proof, range_prove

Modified Yet.

**Review by HaoXuan40404 — APPROVED** [review]

**Pull request merged**
